config/routes.rb
Rails.application.routes.draw do
  #get 'oauth/index'
  root to:'posts#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks',
  }
  devise_scope :user do
    get "user/:id", to: "users/registrations#detail"
    get "signup", to: "users/registrations#new"
    get "login", to: "users/sessions#new"
    get "logout", to: "users/sessions#destroy"
  end
  resources :users do
    collection do
      get 'search', to: 'users#search'
    end
  end
  resources :profiles do
    collection do
      get 'search', to: 'profiles#search'
    end
  end
  resources :posts do
    resources :post_comments, only:[:create, :destroy]
    resources :favorites, only:[:create, :destroy]
    collection do
      get 'search', to: 'posts#search'
      get 'hashtag/:name', to: 'posts#hashtag'
    end
  end

  resources :products do
    resources :product_comments, only:[:create, :destroy]
    collection do
      get 'search', to: 'products#search'
    end
  end

  get 'pages/about'
  get 'pages/privacy'
  get 'pages/service'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :nickname, presence: true, length:{ maximum: 30 }, uniqueness: true
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :product_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  has_many :profile_purpose_relationship
  has_many :purposes, through: :profile_purpose_relationship
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only:[:edit, :update, :show, :destroy]
  before_action :authenticate_user!, only:[:new, :create, :show, :edit, :update, :destroy]
  def index
    @profiles = Profile.page(params[:page]).per(10)
    @purposes = Purpose.all
    @q = Profile.ransack(params[:q])
    @profiles = @q.result.page(params[:page]).per(10)
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    if @profile.save
      redirect_to posts_path, notice: t('view.alert.account')
    else
      render :new
    end
  end

  def show
    @purposes = ProfilePurposeRelationship.where(profile_id: @profile.id).all
    @posts = Post.where(profile_id: @profile.id).order("updated_at DESC")
    @favorites = Favorite.where(profile_id: @profile.id).order("updated_at DESC")
  end

  def edit
    @purposes = ProfilePurposeRelationship.where(profile_id: @profile).pluck(:purpose_id)
  end

  def update
    if @profile.update(profile_params)
      redirect_to profile_path(@profile.id), notice: t('view.alert.update')
    else
      render :edit
    end
  end

  def destroy
    @profile.destroy
    redirect_to posts_path
  end

  def search
    @q = Profile.search(search_params)
    @profiles = @q.result
  end

  private
  def profile_params
    params.require(:profile).permit(:nickname, :image, :age, :skintype, purpose_ids: [])
  end

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def search_params
    params.require(:q).permit(:nickname_cont, :skintype_eq, :age_eq, :purposes_id_eq)
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
  def judge_age(age_value)
    if age_value == 1
      "10代後半~20代前半"
    elsif age_value == 2
      "20代後半"
    elsif age_value == 3
      "30代前半"
    else
      "30代後半以上"
    end
  end

  def judge_skintype(skintype_value)
    if skintype_value == 1
      "混合肌"
    else
      "乾燥肌"
    end
  end

  def judge_purpose(purpose_value)
    if purpose_value == 1
      "仕事"
    else
      "ファッション"
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def judge_age(age_value)
    if age_value == 1
      t("view.profile.late 10's ~ early 20's")
    elsif age_value == 2
      t("view.profile.late 20's")
    elsif age_value == 3
      t("view.profile.early 30's")
    elsif age_value == 4
      t("view.profile.late 30's~")
    elsif age_value == 5
      t("view.profile.age_unknown")
    end
  end

  def judge_skintype(skintype_value)
    if skintype_value == 1
      t('view.profile.normal')
    elsif skintype_value == 2
      t('view.profile.dry')
    elsif skintype_value == 3
      t('view.profile.oily')
    elsif skintype_value == 4
      t('view.profile.mixed')
    elsif skintype_value == 5
      t('view.profile.skin_unknown')
    end
  end
end

app/views/profiles/_form.html.slim
= form_with(model: @profile, local: true) do |f|
  - if @profile.errors.any?
    - @profile.errors.full_messages.each do |msg|
      .error_msg = msg
      br
  .field
    .form-label = t('view.profile.nickname')
    = f.text_field :nickname, class:"form-item"
  br
  .field
    .form-label =  t('view.profile.icon')
    = f.file_field :image, class:"form-item__file"
  br
  .field
    .form-label = t('view.profile.age')
    = f.radio_button :age, 1
    = f.label :age, t("view.profile.late 10's ~ early 20's"), class:"form-label__radio"
    = f.radio_button :age, 2
    = f.label :age, t("view.profile.late 20's"), class:"form-label__radio"
    = f.radio_button :age, 3
    = f.label :age, t("view.profile.early 30's"), class:"form-label__radio"
    = f.radio_button :age, 4
    = f.label :age, t("view.profile.late 30's~"), class:"form-label__radio"
    = f.radio_button :age, 5
    = f.label :age, t("view.profile.age_unknown"), class:"form-label__radio"
  br
  .field
    .form-label = t('view.profile.skintype')
    = f.radio_button :skintype, 1
    = f.label :skintype, t('view.profile.normal'), class:"form-label__radio"
    = f.radio_button :skintype, 2
    = f.label :skintype, t('view.profile.dry'), class:"form-label__radio"
    = f.radio_button :skintype, 3
    = f.label :skintype, t('view.profile.oily'), class:"form-label__radio"
    = f.radio_button :skintype, 4
    = f.label :skintype, t('view.profile.mixed'), class:"form-label__radio"
    = f.radio_button :skintype, 5
    = f.label :skintype, t('view.profile.skin_unknown'), class:"form-label__radio"
  br
  .field
    .form-label = t('view.profile.purpose')
    = f.label :purpose_ids
      - Purpose.all.each do |purpose|
        = f.check_box :purpose_ids,{ multiple: true, checked: @purposes.present? ? @purposes.include?(purpose[:id]) : false, include_hidden: false}, purpose[:id]
        = purpose.purpose
  br
  .actions
    = button_tag "OK", type:"submit", class:"btn btn-success"

app/views/profiles/edit.html.slim
== render "form"

app/views/profiles/index.html.slim
.container
  .search-container
    = search_form_for(@q, url: search_profiles_path) do |f|
      .field
        = f.search_field :nickname_cont, class:"form-control__search", placeholder:t('view.profile.search')
        = button_tag type:"submit", class:"btn btn-search" do
          i.fas.fa-search
  - if @profiles.present?
    ul.profile-list
      - @profiles.each do |profile|
        li.profile-item
          a.list-link href = profile_path(profile.id)
            = image_check(profile.image, "list-icon")
            = profile.nickname
          ul.tag-list
            - if profile.age.present?
              li.tag-item = judge_age(profile.age)
            - if profile.skintype.present?
              li.tag-item = judge_skintype(profile.skintype)
            - profile.profile_purpose_relationship.each do |pur|
              li.tag-item = pur.purpose.purpose
  - else
    p = "該当のユーザーはいません"

  .paginater
    = paginate @profiles

  .search-container__more
    p.title__more = "詳細検索"
    = search_form_for(@q, url: search_profiles_path) do |f|
      .field
        .form-label__more = t('view.profile.age')
        = f.radio_button :age_eq, ""
        = f.label :age_eq, t('view.none'), class:"form-label__radio"
        = f.radio_button :age_eq, 1
        = f.label :age_eq, t("view.profile.late 10's ~ early 20's"), class:"form-label__radio"
        = f.radio_button :age_eq, 2
        = f.label :age_eq, t("view.profile.late 20's"), class:"form-label__radio"
        = f.radio_button :age_eq, 3
        = f.label :age_eq, t("view.profile.early 30's"), class:"form-label__radio"
        = f.radio_button :age_eq, 4
        = f.label :age_eq, t("view.profile.late 30's~"), class:"form-label__radio"
        = f.radio_button :age_eq, 5
        = f.label :age_eq, t("view.profile.age_unknown"), class:"form-label__radio"
      br
      .field
        .form-label__more = t('view.profile.skintype')
        = f.radio_button :skintype_eq, ""
        = f.label :skintype_eq, t('view.none'), class:"form-label__radio"
        = f.radio_button :skintype_eq, 1
        = f.label :skintype_eq, t('view.profile.normal'), class:"form-label__radio"
        = f.radio_button :skintype_eq, 2
        = f.label :skintype_eq, t('view.profile.dry'), class:"form-label__radio"
        = f.radio_button :skintype_eq, 3
        = f.label :skintype_eq, t('view.profile.oily'), class:"form-label__radio"
        = f.radio_button :skintype_eq, 4
        = f.label :skintype_eq, t('view.profile.mixed'), class:"form-label__radio"
        = f.radio_button :skintype_eq, 5
        = f.label :skintype_eq, t('view.profile.skin_unknown'), class:"fgorm-label__radio"
      br
      .field
        .form-label__more = t('view.profile.purpose')
        = f.radio_button :purposes_id_eq, ""
        = f.label :purposes_id_eq, t('view.none'), class:"form-label__radio"
        = f.collection_radio_buttons :purposes_id_eq, @purposes, :id, :purpose
      br
      .field
        = f.search_field :nickname_cont, class:"form-control__search__more", placeholder:t('view.profile.search')
      br
      .field
        = f.submit t('view.get')

app/views/profiles/new.html.slim
h2.pro_title = "プロフィール作成"
p.pro_desc = "投稿やコメントをするためにプロフィールを作成してください"
== render "form"

app/views/profiles/search.html.slim
.container
  .search-container
    = search_form_for(@q, url: search_profiles_path) do |f|
      = f.search_field :nickname_cont, class:"form-control__search", placeholder:t('view.profile.search')
      = button_tag type:"submit", class:"btn btn-search" do
        i.fas.fa-search
  - if @profiles.present?
    ul.profile-list
      - @profiles.each do |profile|
        li.profile-item
          a.list-link href = profile_path(profile.id)
            = image_check(profile.image, "list-icon")
            = profile.nickname
          ul.tag-list
            - if profile.age.present?
              li.tag-item = judge_age(profile.age)
            - if profile.skintype.present?
              li.tag-item = judge_skintype(profile.skintype)
            - profile.profile_purpose_relationship.each do |pur|
              li.tag-item = pur.purpose.purpose
  - else
    p = "該当のユーザーはいません"

app/views/profiles/show.html.slim
.container
  .profile
    .profile-thum
      = image_check(@profile.image, "profile-image")
    .profile-desc
      h2.profile-name = @profile.nickname
      ul.tag-list__show
        - if @profile.age.present?
          li.tag-item__show = judge_age(@profile.age)
          br
        - if @profile.skintype.present?
          li.tag-item__show = judge_skintype(@profile.skintype)
          br
        - @purposes.each do |pur|
          li.tag-item__show = pur.purpose.purpose
          br
        - if current_profile.present? && @profile.id == current_profile.id
          .link-list
            = link_to t('view.profile.edit profile'), edit_profile_path(current_profile.id), class:"mypage-link"
            nsbp
            = link_to t('view.profile.parsonal info'), edit_user_registration_path, class:"mypage-link"
  .tab-list
    input class="post-label" type="radio" checked=true name="lists" value=1 id="post"
    label for = "post" class = "label button first"
      | 投稿一覧
    input class="post-label" type="radio" name="lists" value=2 id= "fav"
    label for = "fav" class = "label button second"
      | お気に入り
  #profile-postlist
    ul.post-list
      - @posts.each do |post|
        li.post-item
          - if video_check(post.images[0]) == true
            = link_to post_path(post.id) do
              video.post-wrap src = post.images[0] controls = true
          - else
            = link_to post_path(post.id) do
              img.post-wrap src = post.images[0]

  #favorite-list
    ul.post-list
      - @favorites.each do |fav|
        li.post-item
          - if video_check(fav.post.images[0]) == true
            = link_to post_path(fav.post.id) do
              video.post-wrap src = fav.post.images[0] controls = true
          - else
            = link_to post_path(fav.post.id) do
              img.post-wrap src = fav.post.images[0]

javascript:
  $(function(){
    $('input[name="lists"]').change(function(){
      var result = $(this).val();
      console.log(result);
      if(result == "2"){
        document.getElementById("profile-postlist").style.display="none";
        document.getElementById("favorite-list").style.display="block";
      }else{
        document.getElementById("favorite-list").style.display="none";
        document.getElementById("profile-postlist").style.display="block";
      };
    });
  });