config/routes.rb
Rails.application.routes.draw do
  #get 'oauth/index'
  root to:'posts#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks',
  }
  devise_scope :user do
    get "user/:id", to: "users/registrations#detail"
    get "signup", to: "users/registrations#new"
    get "login", to: "users/sessions#new"
    get "logout", to: "users/sessions#destroy"
  end
  resources :users do
    collection do
      get 'search', to: 'users#search'
    end
  end
  resources :profiles do
    collection do
      get 'search', to: 'profiles#search'
    end
  end
  resources :posts do
    resources :post_comments, only:[:create, :destroy]
    resources :favorites, only:[:create, :destroy]
    collection do
      get 'search', to: 'posts#search'
      get 'hashtag/:name', to: 'posts#hashtag'
    end
  end

  resources :products do
    resources :product_comments, only:[:create, :destroy]
    collection do
      get 'search', to: 'products#search'
    end
  end

  get 'pages/about'
  get 'pages/privacy'
  get 'pages/service'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :profile
  belongs_to :post
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @favorite = current_profile.favorites.create(post_id: @post.id)
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_profile.favorites.find_by(post_id: @post.id).destroy
  end
end

app/views/favorites/_favorite.html.slim
- if current_profile.present? &&  post.profile_id != current_profile.id
  - if favorite.present?
    = link_to post_favorite_path(favorite, post_id: post.id), method: :delete, id:"delete", remote: true
      i.fas.fa-heart.fa-lg
  - else
    = link_to post_favorites_path(post), method: :post, id:"like", remote: true
     i.far.fa-heart.fa-lg

app/views/favorites/create.js.slim
|$("#like").html("
= j(render 'favorites/favorite', { post: @post, favorite: @favorite })
|");

app/views/favorites/destroy.js.slim
|$("#delete").html("
= j(render 'favorites/favorite', { post: @post, favorite: @favorite })
|");