config/routes.rb
Rails.application.routes.draw do
  #get 'oauth/index'
  root to:'posts#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks',
  }
  devise_scope :user do
    get "user/:id", to: "users/registrations#detail"
    get "signup", to: "users/registrations#new"
    get "login", to: "users/sessions#new"
    get "logout", to: "users/sessions#destroy"
  end
  resources :users do
    collection do
      get 'search', to: 'users#search'
    end
  end
  resources :profiles do
    collection do
      get 'search', to: 'profiles#search'
    end
  end
  resources :posts do
    resources :post_comments, only:[:create, :destroy]
    resources :favorites, only:[:create, :destroy]
    collection do
      get 'search', to: 'posts#search'
      get 'hashtag/:name', to: 'posts#hashtag'
    end
  end

  resources :products do
    resources :product_comments, only:[:create, :destroy]
    collection do
      get 'search', to: 'products#search'
    end
  end

  get 'pages/about'
  get 'pages/privacy'
  get 'pages/service'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  validates :images, presence: true
  validates :content, length:{ maximum: 300 }
  mount_uploaders :images, VideoUploader
  has_many :post_hashtag_relationships, through: :post_hashtag_relationships, source: :hashtags
  belongs_to :profile
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_profiles, through: :favorites, source: :profile
  validates_integrity_of :images

  after_create do
    post = Post.find_by(id: self.id)
    unless self.content.nil?
      hashtags = self.content.scan(/#[\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
      hashtags.each do |hash|
        hash = hash.delete('#')
        hash_log = Hashtag.find_or_create_by(hashtag: hash)
        PostHashtagRelationship.create!(post_id: post.id, hashtag_id: hash_log.id)
      end
    end
  end

  after_update do
    post = Post.find_by(id: self.id)
    PostHashtagRelationship.where(post_id: post.id).delete_all
    unless self.content.nil?
      hashtags = self.content.scan(/#[\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
      hashtags.each do |hash|
        hash = hash.delete('#')
        hash_log = Hashtag.find_or_create_by(hashtag: hash)
        unless PostHashtagRelationship.find_by(post_id: post.id, hashtag_id: hash_log.id)
          PostHashtagRelationship.create!(post_id: post.id, hashtag_id: hash_log.id)
        end
      end
    end
  end

  scope :search_content, ->(word){ where('content LIKE ?', "#{word}")}


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only:[:edit, :update, :show, :destroy]
  before_action :authenticate_user!, only:[:new, :create, :edit, :update, :destroy]
  before_action :current_profile!, only:[:new, :create, :edit, :update, :destroy]
  def index
    @posts = Post.page(params[:page]).per(12).includes(:profile).order('updated_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.profile_id = current_profile.id
    if @post.save
      redirect_to posts_path, notice: t('view.alert.post')
    else
      render :new
    end
  end

  def show
    @post_comments = @post.post_comments.includes(:profile)
    @post_comment = @post.post_comments.build
    unless current_profile.nil?
      @favorite = current_profile.favorites.find_by(post_id: @post.id)
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: t('view.alert.update')
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: t('view.alert.delete')
  end

  def hashtag
    tag = Hashtag.find_by(hashtag: params[:name])
    @hashs = PostHashtagRelationship.where(hashtag_id: tag.id).order('updated_at DESC')
  end

  def search
    @posts = Post.where("content LIKE ?","%#{params[:search]}%")
  end

  private

  def post_params
    params.require(:post).permit({images:[]}, :content)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def current_profile!
    unless current_profile.present?
      redirect_to new_profile_path, notice: t('view.alert.make_profile')
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def change_hash(post)
    h(post).gsub(/#[\w\p{Han}ぁ-ヶｦ-ﾟー]+/){|word| link_to word, "/posts/hashtag/#{word}".delete('#') }.html_safe
  end

  def video_check(target)
    if target.to_s.end_with?(".mp4") || target.to_s.end_with?(".gif") || target.to_s.end_with?(".mov")
      return true
    end
  end
end

app/views/posts/_form.html.slim
= form_with(model: @post, local: true) do |f|
  - if @post.errors.any?
    - @post.errors.full_messages.each do |msg|
      .error_msg = msg
      br
  .field
    .form-label = t('view.post.images')
    = f.file_field :images, multiple: true, class:"form-item__file"
    = f.file_field :images, multiple: true, class:"form-item__file"
    = f.file_field :images, multiple: true, class:"form-item__file"
  br
  .field
    .form-label = t('view.post.content')
    = f.text_area :content, class:"form-item__textarea"
  br
  .actions
    = button_tag t('view.submit'), type:"submit", class:"btn btn-success__textarea"

app/views/posts/edit.html.slim
== render "form"

app/views/posts/hashtag.html.slim
.container
  ul.post-list
    - @hashs.each do |hash|
      li.post-item
        - if video_check(hash.post.images[0]) == true
          = link_to post_path(hash.post.id) do
            video.post-wrap src = hash.post.images[0] controls = true
        - else
          = link_to post_path(hash.post.id)
            img.post-wrap src = hash.post.images[0]

app/views/posts/index.html.slim
.container
  .search-container
    = form_tag search_posts_path, method: :get do
      = text_field_tag :search, "", placeholder:t('view.post.search'),class:"form-control__search"
      = button_tag type: "submit", class:"btn btn-search" do
        i.fas.fa-search

  ul.post-list
    - @posts.each do |post|
      li.post-item
        - if video_check(post.images[0]) == true
          = link_to post_path(post.id) do
            video.post-wrap src = post.images[0] controls = true
        - else
          = link_to post_path(post.id) do
            img.post-wrap src = post.images[0]

  .paginater
    = paginate @posts

app/views/posts/new.html.slim
== render "form"

app/views/posts/search.html.slim
.container
  - if @posts.present?
    ul.post-list
      - @posts.each do |post|
        li.post-item
          - if video_check(post.images[0]) == true
            = link_to post_path(post.id) do
              video.post-wrap src = post.images[0] controls = true
          - else
            = link_to post_path(post.id)
              img.post-wrap src = post.images[0]
  - else
    p = "該当の投稿はありません"

app/views/posts/show.html.slim
- set_meta_tags title: @post.content, description: @post.content
.container
  .post
    .post-profile
      = image_check(@post.profile.image, "post-icon")
      = @post.profile.nickname
      - @post.images.each_with_index do |post_img, i|
        div id = "post-image__#{i}"
          - if video_check(post_img) == true
            video.post-content src = post_img controls = true
          - else
            img.post-content src = post_img
    #button-container
      #button-list
        - @post.images.each_with_index do |post_img, i|
          label
            input class="radio-images" type="radio" name="images" value=i
            span.images-label
    == render partial: "favorites/favorite", locals:{ favorite: @favorite, post: @post }
    - if current_profile.present? && @post.profile.id == current_profile.id
      = link_to edit_post_path(@post.id)
        i.fas.fa-edit.fa-lg
      = link_to post_path(@post.id), method: :delete, data:{ confirm: "OK?" }
        i.fas.fa-trash-alt.fa-lg
    br
    = change_hash(@post.content)
  h3.comment-label = t('view.comments')
  #post_comments_area.comments
    == render partial: "post_comments/index", locals:{ post_comments: @post_comments, post: @post }

  - if current_profile.present?
    == render partial: "post_comments/form", locals:{ post_comment: @post_comment, post: @post }


javascript:
  $(function(){
    $('input[name="images"]').change(function(){
      var result = $(this).val();
      if(result == "0"){
        document.getElementById("post-image__0").style.display="block";
      }else{
        document.getElementById("post-image__0").style.display="none";
      };

      if(document.getElementById("post-image__1") != null){
        if(result == "1"){
          document.getElementById("post-image__1").style.display="block";
        }else{
          document.getElementById("post-image__1").style.display="none";
        };
      };

      if(document.getElementById("post-image__2") != null){
        if(result == "2"){
          document.getElementById("post-image__2").style.display="block";
        }else{
          document.getElementById("post-image__2").style.display="none";
        };
      };
    });
  });