config/routes.rb
Rails.application.routes.draw do
  #get 'oauth/index'
  root to:'posts#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks',
  }
  devise_scope :user do
    get "user/:id", to: "users/registrations#detail"
    get "signup", to: "users/registrations#new"
    get "login", to: "users/sessions#new"
    get "logout", to: "users/sessions#destroy"
  end
  resources :users do
    collection do
      get 'search', to: 'users#search'
    end
  end
  resources :profiles do
    collection do
      get 'search', to: 'profiles#search'
    end
  end
  resources :posts do
    resources :post_comments, only:[:create, :destroy]
    resources :favorites, only:[:create, :destroy]
    collection do
      get 'search', to: 'posts#search'
      get 'hashtag/:name', to: 'posts#hashtag'
    end
  end

  resources :products do
    resources :product_comments, only:[:create, :destroy]
    collection do
      get 'search', to: 'products#search'
    end
  end

  get 'pages/about'
  get 'pages/privacy'
  get 'pages/service'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_link.html.slim
- if current_user.present? && current_profile.nil?
  = link_to "+", new_profile_path, class:"btn btn-plus"
- elsif current_profile.present?
  = link_to "+", new_post_path, class:"btn btn-plus"
- else

app/views/layouts/application.html.slim
doctype html
html
  head
    title Bpals
    = csrf_meta_tags
    = csp_meta_tag
    = display_meta_tags(default_meta_tags)
    meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet"
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag('favicon.ico')
  body
    header
      .header
        .header-inner
          .header-wrap
            a.title-link href = "/" = "B-PALs"
          #nav-drawer
            input id="nav-input" type="checkbox" class="nav-unshown"
            label id="nav-open" for="nav-input"
              span
            label class="nav-unshown" id="nav-close" for="nav-input"
            #nav-content
              .menu
                h2.menu-title Menu
                ul.menu-list
                  li.menu-item
                    = link_to t('view.post.index'), posts_path, class: "menu-link"
                  li.menu-item
                    = link_to t('view.post.new'), new_post_path ,class: "menu-link"
                  li.menu-item
                    = link_to t('view.profile.list'), profiles_path, class: "menu-link"
                  li.menu-item
                    = link_to t('view.product.list'), products_path, class: "menu-link"
                  - if current_user.present? && current_profile.present?
                    li.menu-item
                      = link_to t('view.mypage'), profile_path(current_profile.id), class:"menu-link"
                  - if current_user.present? && current_profile.present? && current_user.admin_flag == true
                    li.menu-item
                      = link_to t('view.user.list'), users_path, class:"menu-link"
                    li.menu-item
                      = link_to t('view.product.new'), new_product_path, class:"menu-link"
                  - if current_user.present?
                    li.menu-item
                      = link_to t('view.logout'), destroy_user_session_path, method: :delete, class: "menu-link"
                  - else
                    li.menu-item
                      = link_to t('devise.shared.links.sign_up'), new_user_registration_path, class: "menu-link"
                    li.menu-item
                      = link_to t('devise.shared.links.sign_in'), new_user_session_path, class: "menu-link"

    main.main
      .alert = notice
      = yield
    - if current_user.present?
      .shortcut-box
        ul.shortcut-list
          li.shortcut-item
            = link_to new_post_path, class:"shortcut-link"
              = image_tag "/post.png"
              p = t('view.post.new')
          li.shortcut-item
            = link_to profiles_path, class:"shortcut-link"
              = image_tag "/profile.png"
              p = t('view.profile.list')
          li.shortcut-item
            = link_to products_path, class:"shortcut-link"
              = image_tag "/product.png"
              p = t('view.product.list')
          - if current_profile.present?
            li.shortcut-item
              = link_to profile_path(current_profile.id), class:"shortcut-link"
                = image_tag "/icon.png"
                p = t('view.mypage')
          - else
            li.shortcut-item.__banned
              = link_to "javascriot:void(0)", class:"shortcut-link"
                = image_tag "/icon.png"
                p = "my page"


    footer
      .footer-container
        .footer-list
          - if user_signed_in?
            = link_to t('view.logout'), destroy_user_session_path, method: :delete, class: "footer-item"
          - else
            = link_to t('devise.shared.links.sign_up'), new_user_registration_path, class: "footer-item"
            span.slash = " / "
            = link_to t('devise.shared.links.sign_in'), new_user_session_path, class: "footer-item"
          span.slash = " / "
          = link_to t('view.terms_of_service'), pages_service_path, class:"footer-item"
          span.slash = " / "
          = link_to t('view.terms_of_privacy'), pages_privacy_path, class:"footer-item"
        .company-info
          |&copy; 2019 B-PALs